In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd 

# Import dataset:
url = r"C:\Users\charc\project_files\dataset_final.csv"

# Assign column names to dataset:
names = ['image_number','ang1','ang2','ang3','ang4','ang5','ang6','ang7','ang8','ang9','ang10','ang11','ang12','ang13','ang14','ang15','ang16', 'Class']

# Convert dataset to a pandas dataframe:
dataset = pd.read_csv(url, names=names) 

# Use head() function to return the first 5 rows: 
dataset.head() 
# Assign values to the X and y variables:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 17].values 

# Split dataset into random train and test subsets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) 

# Standardize features by removing mean and scaling to unit variance:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test) 

# Use the KNN classifier to fit data:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train) 

# Predict y data with classifier: 
y_predict = classifier.predict(X_test)

# Print results: 
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[78  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 73  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 42  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 71  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 56  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 86  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 52  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 69  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0 50  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 69  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1 60  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 60  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0 67  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 72  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 59  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 58  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 74  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 41  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 32  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 31  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 70  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 89]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00        78
           B       1.00      1.00      1.00        73
           C       1.00      1.00      1.00        42
           D       0.98      1.00      0.99        47
           E       1.00      1.00      1.00        71
           F       1.00      1.00      1.00        56
           G       1.00      0.99      0.99        87
           H       1.00      1.00      1.00        35
           I       0.98      1.00      0.99        52
           K       0.99      1.00      0.99        69
           L       1.00      0.98      0.99        51
           M       0.99      1.00      0.99        69
           N       1.00      0.97      0.98        62
           O       1.00      1.00      1.00        60
           P       1.00      0.99      0.99        68
           Q       1.00      1.00      1.00        72
           R       1.00      1.00      1.00        59
           S       1.00      1.00      1.00        58
           T       0.99      1.00      0.99        74
           U       0.93      0.95      0.94        43
           V       0.94      0.91      0.93        35
           W       1.00      1.00      1.00        31
           X       1.00      1.00      1.00        70
           Y       1.00      1.00      1.00        89

    accuracy                           0.99      1451
   macro avg       0.99      0.99      0.99      1451
weighted avg       0.99      0.99      0.99      1451

In [48]:
import pandas as pd 

# Import dataset:
url = r"C:\Users\charc\project_files\dataset_final.csv"

# Assign column names to dataset:
names = ['image_number','ang1','ang2','ang3','ang4','ang5','ang6','ang7','ang8','ang9','ang10','ang11','ang12','ang13','ang14','ang15','ang16', 'Class']

# Convert dataset to a pandas dataframe:
dataset = pd.read_csv(url, names=names) 

# Use head() function to return the first 5 rows: 
dataset

,image_number,ang1,ang2,ang3,ang4,ang5,ang6,ang7,ang8,ang9,ang10,ang11,ang12,ang13,ang14,ang15,ang16,Class
0,A_001.jpg,135.06,162.47,157.87,35.99,159.97,7.91,179.50,169.72,2.21,174.17,171.44,4.97,170.13,178.51,2.18,167.38,A
1,A_002.jpg,130.04,160.15,156.04,37.24,158.21,7.57,176.86,169.21,2.19,174.17,173.42,2.64,172.09,175.56,4.38,172.58,A
2,A_003.jpg,129.43,160.45,154.80,38.73,159.05,7.45,177.05,169.89,2.56,174.35,174.75,2.15,171.86,173.88,5.63,172.02,A
3,A_004.jpg,129.74,159.61,156.31,37.59,158.75,8.12,177.15,169.16,3.24,173.46,174.30,2.60,171.64,174.94,4.51,171.73,A
4,A_005.jpg,131.33,159.41,156.49,37.12,159.22,7.10,177.55,169.63,2.26,174.74,175.13,1.25,173.24,172.77,7.42,173.77,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4831,Y_247.jpg,150.09,173.11,156.71,34.71,169.42,0.42,177.43,179.03,6.30,179.10,174.73,9.91,179.06,165.96,177.64,177.87,Y
4832,Y_248.jpg,151.51,172.94,157.74,33.64,171.29,2.85,178.87,179.40,7.60,179.26,172.97,11.30,179.44,165.24,176.46,177.34,Y
4833,Y_249.jpg,152.15,173.84,157.44,33.69,167.96,0.66,177.49,178.65,5.61,179.53,174.11,9.56,179.47,165.84,177.30,179.12,Y
4834,Y_250.jpg,155.77,173.74,158.93,32.87,168.98,1.71,179.00,178.47,5.70,179.84,174.73,8.29,179.72,166.72,176.91,179.14,Y
4835,Y_251.jpg,153.38,173.65,157.06,33.40,170.62,3.09,178.79,179.38,7.39,179.43,173.49,9.87,179.47,165.09,176.38,178.30,Y

In [66]:
from sklearn.model_selection import train_test_split

#Importing the Decision Tree from scikit-learn library
from sklearn.metrics  import f1_score,accuracy_score
from sklearn.tree import DecisionTreeClassifier

import pandas as pd 

# Import dataset:
url = r"C:\Users\charc\project_files\dataset_final.csv"

# Assign column names to dataset:
names = ['image_number','ang1','ang2','ang3','ang4','ang5','ang6','ang7','ang8','ang9','ang10','ang11','ang12','ang13','ang14','ang15','ang16', 'Class']

# Convert dataset to a pandas dataframe:
dataset = pd.read_csv(url, names=names) 

# Use head() function to return the first 5 rows: 
dataset.head() 
# Assign values to the X and y variables:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 17].values 

# Split dataset into random train and test subsets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35) 

# Standardize features by removing mean and scaling to unit variance:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test) 

DT= DecisionTreeClassifier()
DT.fit(X_train,y_train)
pred=DT.predict(X_test)
 
# for classification we use accuracy and F1 score
print("Accuracy for Decision Tree is ",accuracy_score(y_test,pred))
print("F1 score for Decision Tree is ",f1_score(y_test,pred,pos_label='positive',average='macro'))

Accuracy for Decision Tree is  0.9734199645599527
F1 score for Decision Tree is  0.9722426370470897

D:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1298: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn("Note that pos_label (set to %r) is ignored when "